# Credit to https://github.com/APDevTeam/Movecraft/actions for this
name: Java CI

on: [push, pull_request]

jobs:
  # Build 1.19.3 NMS
  nms_version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'
    - name: Setup BuildTools
      run: mkdir BuildTools && wget -O BuildTools/BuildTools.jar https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
    - name: Check 1.19.3 Spigot
      id: wild
      run: test -f ~/.m2/repository/org/spigotmc/spigot/1.19.3-R0.1-SNAPSHOT/spigot-1.19.3-R0.1-SNAPSHOT.jar && echo "::set-output name=sucess::true" || echo "::set-output name=sucess::false"
    - name: Check 1.19.3 Spigot (Mojang)
      id: wildMojang
      run: test -f ~/.m2/repository/org/spigotmc/spigot/1.19.3-R0.1-SNAPSHOT/spigot-1.19.3-R0.1-SNAPSHOT-remapped-mojang.jar && echo "::set-output name=sucess::true" || echo "::set-output name=sucess::false"
    - name: Check 1.19.3 Spigot (Obf)
      id: wildObf
      run: test -f ~/.m2/repository/org/spigotmc/spigot/1.19.3-R0.1-SNAPSHOT/spigot-1.19.3-R0.1-SNAPSHOT-remapped-obf.jar && echo "::set-output name=sucess::true" || echo "::set-output name=sucess::false"
    - name: Build 1.19.3
      if: steps.wild.outputs.sucess != 'true' || steps.wildMojang.outputs.sucess != 'true' || steps.wildObf.outputs.sucess != 'true'
      run: cd BuildTools && java -jar BuildTools.jar --rev 1.19.3 --compile craftbukkit --compile-if-changed

  # Build RoyalChat using Maven
  build-rchat:
    runs-on: ubuntu-latest
    needs: nms_version

    steps:
      - name: Checkout RoyalChat
        uses: actions/checkout@v3
        with:
          repository: WMCAlliance/RoyalChat
          path: royalchat

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven
          
      - name: Install RoyalChat with Maven
        working-directory: royalchat
        run: mvn -B clean install

  # Build RoyalCommands using Maven
  build-rcmds:
    runs-on: ubuntu-latest
    needs: build-rchat

    steps:
    - name: Checkout RoyalCommands
      uses: actions/checkout@v3
        
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: maven

    - name: Install RoyalCommands with Maven
      run: mvn -B clean install
      
    - name: Build RoyalCommands with Maven
      run: mvn -B clean package
