name: Maven Build

on:
  push:
  pull_request:

jobs:
  # Build RoyalCommands using Maven
  build-rcmds:
    runs-on: ubuntu-latest
    if: "!contains(github.event.commits[0].message, '[ci-skip]')"

    steps:
    - name: Checkout RoyalCommands
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: maven

    - name: Build RoyalCommands with Maven
      env:
        GITHUB_USERNAME: ${{ secrets.USERNAME }}
        GITHUB_TOKEN: ${{ secrets.PAT }}
      run: mvn clean package --settings settings.xml

    - uses: actions/upload-artifact@v3
      with:
        name: RoyalCommands (#${{ github.run_number }})
        path: |
          /home/runner/work/RoyalCommands/RoyalCommands/modules/RoyalCommands/target/*.jar
          /home/runner/work/RoyalCommands/RoyalCommands/modules/RoyalCommands/target/RoyalCommands/
